DOMAIN = "miningpoolhub"

CONF_CURRENCY_NAMES = "currency_names"
CONF_FIAT_CURRENCY = "fiat_currency"

SENSOR_PREFIX = "MiningPoolHub  "

ATTR_ACTIVE_WORKERS = "active_workers"
ATTR_AVERAGE_HASHRATE_24h = "average_hashrate_24h"
ATTR_CURRENT_HASHRATE = "current_hashrate"
ATTR_CURRENCY = "currency"
ATTR_INVALID_SHARES = "invalid_shares"
ATTR_VALID_SHARES = "valid_shares"
ATTR_LAST_UPDATE = "last_update"
ATTR_BALANCE_CONFIRMED = "balance_confirmed"
ATTR_BALANCE_UNCONFIRMED = "balance_unconfirmed"
ATTR_BALANCE_AUTO_EXCHANGE_CONFIRMED = "balance_auto_exchange_confirmed"
ATTR_BALANCE_AUTO_EXCHANGE_UNCONFIRMED = "balance_auto_exchange_unconfirmed"
ATTR_BALANCE_ON_EXCHANGE = "balance_on_exchange"
ATTR_RECENT_CREDITS_24_HOURS = "recent_credits_24_hours"
ATTR_SINGLE_COIN_LOCAL_CURRENCY = "single_coin_in_local_currency"
ATTR_TOTAL_UNPAID_FIAT = "fiat_currency_unpaid_total"
ATTR_COINS_PER_MINUTE = "coins_per_minute"

COINGECKO_API_ENDPOINT = "https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies="
