DOMAIN = "miningpoolhub"

CONF_ACCESS_TOKEN = "access_token"
CONF_CURRENCY_NAMES = "currency_names"
CONF_ID = "id"
CONF_NAME_OVERRIDE = "name_override"
CONF_UPDATE_FREQUENCY = "update_frequency"


SENSOR_PREFIX = "MiningPoolHub  "

ATTR_ACTIVE_WORKERS = "active_workers"
ATTR_CURRENT_HASHRATE = "current_hashrate"
ATTR_INVALID_SHARES = "invalid_shares"
ATTR_LAST_UPDATE = "last_update"
ATTR_REPORTED_HASHRATE = "reported_hashrate"
ATTR_STALE_SHARES = "stale_shares"
ATTR_UNPAID = "unpaid"
ATTR_VALID_SHARES = "valid_shares"
ATTR_START_BLOCK = "start_block"
ATTR_END_BLOCK = "end_block"
ATTR_AMOUNT = "amount"
ATTR_TXHASH = "txhash"
ATTR_PAID_ON = "paid_on"
ATTR_AVERAGE_HASHRATE_24h = "average_hashrate_24h"
ATTR_UNCONFIRMED = "unconfirmed"
ATTR_SINGLE_COIN_LOCAL_CURRENCY = "single_coin_in_local_currency"
ATTR_TOTAL_UNPAID_LOCAL_CURRENCY = "unpaid_in_local_currency"
ATTR_COINS_PER_MINUTE = "coins_per_minute"

COINGECKO_API_ENDPOINT = "https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies="